export const SET_PROJECTS = "SET_PROJECTS";
export const SET_PROJECTS_BY_ID = "SET_PROJECTS_BY_ID";
export const SET_PROJECTS_ALL_IDS = "SET_PROJECTS_ALL_IDS";
export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
export const UPDATE_PROJECTS = "UPDATE_PROJECTS";
